repos:
- repo: https://github.com/returntocorp/semgrep
  rev: 'v1.14.0'
  hooks:
    - id: semgrep
      exclude: "(.)*/tests|tests"
      args: [
        '--config',
        'p/owasp-top-ten',
        '--config',
        'p/cwe-top-25',
        '--config',
        'p/gitleaks',
        '--error',
        '--skip-unknown-extensions',
        '--exclude-rule=python.sqlalchemy.security.audit.avoid-sqlalchemy-text.avoid-sqlalchemy-text'
      ]
      stages: [commit]
