name: Install StartLeft
description: 'Install StartLeft'
inputs:
  python-version:
    description: 'Python Version'
    required: true

runs:
  using: "composite"
  steps:

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python-version }}

      - name: Update pip version to 23.0.1
        run: python -m pip install --upgrade pip==23.0.1
        shell: bash

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@55fcdfa9328aed658432c22011bec2873cd8e69f # Securely point to hash commit for v1

      - name: Configure Graphviz in Windows
        if: runner.os == 'Windows'
        shell: bash
        run: |
          pip install --global-option=build_ext --global-option="-IC:\Program files\Graphviz\include" --global-option="-LC:\Program files\Graphviz\lib" pygraphviz==1.10
          echo "C:\Program Files\Graphviz\bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: pip install -e ".[setup,test]"
        shell: bash

        # This step MUST be after the general installation of StartLeft
      - name: Install libmagic in Windows
        if: runner.os == 'Windows'
        run: pip install python-magic-bin
        shell: bash

