# coding: utf-8
# version file generated by setuptools_scm
# don't change and keep it as is to avoid errors with
# these version variables
version = 'development-version'
version_tuple = 'development-version'
