name: Install doc dependencies
description: 'Install doc dependencies'

runs:
  using: "composite"
  steps:

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Configure git username
      run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      shell: bash

    - name: Install doc dependencies
      run: pip install -r docs/requirements.txt
      shell: bash
