FROM python:3.8-alpine AS startleft-base

WORKDIR /usr/src/app

RUN apk update && \
    apk upgrade && \
    apk add git && \
    apk add geos && \
    apk add graphviz-dev

RUN apk --no-cache add lapack libstdc++ libmagic geos-dev && \
    apk --no-cache add --virtual .builddeps g++ gcc gfortran musl-dev lapack-dev re2 re2-dev py3-pybind11-dev

COPY . .

RUN pip install --upgrade pip

RUN pip install .


FROM python:3.8-alpine

WORKDIR /app

RUN apk update && \
    apk add libmagic && \
    apk add re2 && \
    apk add lapack && \
    apk add cblas && \
    apk add geos

# Due to CVE-2023-46045 detected in v9.x.y of graphviz and lower ones,
# we need to install the latest version of graphviz from the alpine edge repository
RUN apk add graphviz --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community

COPY --from=startleft-base /usr/local/lib/python3.8/site-packages /usr/local/lib/python3.8/site-packages

COPY --from=startleft-base /usr/local/bin/startleft /usr/local/bin/startleft

CMD ["startleft", "server", "--host", "0.0.0.0"]
