from .impl.component_identifier_by_shape_text import ComponentIdentifierByShapeText
from .impl.create_component_by_shape_text import CreateComponentByShapeText
from .impl.create_component_by_master_page_name import CreateComponentByMasterPageName
from .impl.component_identifier_by_master_page_name import ComponentIdentifierByMasterPageName
